-- MySQL Script generated by MySQL Workbench
-- Wed Jul 10 15:55:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`acudiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`acudiente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`acudiente` (
  `idAcudiente` INT NOT NULL,
  `nombresAcudiente` VARCHAR(45) NOT NULL,
  `apellidosAcudiente` VARCHAR(45) NOT NULL,
  `telefonoAcudiente` VARCHAR(10) NOT NULL,
  `idParentezco` TINYINT(2) NULL,
  PRIMARY KEY (`idAcudiente`),
  CONSTRAINT `parentezco`
    FOREIGN KEY (`idParentezco`)
    REFERENCES `mydb`.`parentezco` (`idparentezco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `parentezco_idx` ON `mydb`.`acudiente` (`idParentezco` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asignatura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asignatura` (
  `idAsignatura` TINYINT(3) NOT NULL,
  `asignatura` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idAsignatura`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `asignatura_UNIQUE` ON `mydb`.`asignatura` (`asignatura` ASC) VISIBLE;

CREATE UNIQUE INDEX `idAsignatura_UNIQUE` ON `mydb`.`asignatura` (`idAsignatura` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`asignatura_has_horasDisponibles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asignatura_has_horasDisponibles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asignatura_has_horasDisponibles` (
  `asignatura_idAsignatura` INT NOT NULL,
  `agenda_idagenda` INT NOT NULL,
  PRIMARY KEY (`asignatura_idAsignatura`, `agenda_idagenda`),
  CONSTRAINT `fk_asignatura_has_agenda_asignatura1`
    FOREIGN KEY (`asignatura_idAsignatura`)
    REFERENCES `mydb`.`asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_has_agenda_agenda1`
    FOREIGN KEY (`agenda_idagenda`)
    REFERENCES `mydb`.`horasDisponibles` (`idagenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_asignatura_has_agenda_agenda1_idx` ON `mydb`.`asignatura_has_horasDisponibles` (`agenda_idagenda` ASC) VISIBLE;

CREATE INDEX `fk_asignatura_has_agenda_asignatura1_idx` ON `mydb`.`asignatura_has_horasDisponibles` (`asignatura_idAsignatura` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clase` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clase` (
  `idClase` INT NOT NULL,
  `profesor_persona` INT NOT NULL,
  `idAsignatura` TINYINT(3) NOT NULL,
  `idAgenda` INT NOT NULL,
  PRIMARY KEY (`idClase`),
  CONSTRAINT `profesor`
    FOREIGN KEY (`profesor_persona`)
    REFERENCES `mydb`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `asignatura`
    FOREIGN KEY (`idAsignatura`)
    REFERENCES `mydb`.`asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `agenda`
    FOREIGN KEY (`idAgenda`)
    REFERENCES `mydb`.`horasDisponibles` (`idagenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `profesor_idx` ON `mydb`.`clase` (`profesor_persona` ASC) VISIBLE;

CREATE INDEX `asignatura_idx` ON `mydb`.`clase` (`idAsignatura` ASC) VISIBLE;

CREATE INDEX `agenda_idx` ON `mydb`.`clase` (`idAgenda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `idPersona` INT NOT NULL,
  `creditos` INT NULL,
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_estudiante_persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante_has_acudiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estudiante_has_acudiente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estudiante_has_acudiente` (
  `estudiante_idPersona` INT NOT NULL,
  `acudiente_idAcudiente` INT NOT NULL,
  PRIMARY KEY (`estudiante_idPersona`, `acudiente_idAcudiente`),
  CONSTRAINT `fk_estudiante_has_acudiente_estudiante`
    FOREIGN KEY (`estudiante_idPersona`)
    REFERENCES `mydb`.`estudiante` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_has_acudiente_acudiente1`
    FOREIGN KEY (`acudiente_idAcudiente`)
    REFERENCES `mydb`.`acudiente` (`nombresAcudiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estudiante_has_acudiente_acudiente1_idx` ON `mydb`.`estudiante_has_acudiente` (`acudiente_idAcudiente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante_has_clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estudiante_has_clase` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estudiante_has_clase` (
  `estudiante_idPersona` INT NOT NULL,
  `clase_idClase` INT NOT NULL,
  PRIMARY KEY (`estudiante_idPersona`, `clase_idClase`),
  CONSTRAINT `fk_estudiante_has_clase_estudiante1`
    FOREIGN KEY (`estudiante_idPersona`)
    REFERENCES `mydb`.`estudiante` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_has_clase_clase1`
    FOREIGN KEY (`clase_idClase`)
    REFERENCES `mydb`.`clase` (`idClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estudiante_has_clase_clase1_idx` ON `mydb`.`estudiante_has_clase` (`clase_idClase` ASC) VISIBLE;

CREATE INDEX `fk_estudiante_has_clase_estudiante1_idx` ON `mydb`.`estudiante_has_clase` (`estudiante_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`horasDisponibles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`horasDisponibles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`horasDisponibles` (
  `idagenda` INT NOT NULL,
  `FechaHora` DATETIME NULL,
  PRIMARY KEY (`idagenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parentezco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`parentezco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`parentezco` (
  `idparentezco` TINYINT(2) NOT NULL,
  `descripcionParentezco` VARCHAR(45) NULL,
  PRIMARY KEY (`idparentezco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idPersona` INT NOT NULL,
  `nombresPersona` VARCHAR(20) NOT NULL,
  `apellidosPersona` VARCHAR(20) NOT NULL,
  `direccionPersona` VARCHAR(30) NOT NULL,
  `telefonoPersona` VARCHAR(10) NOT NULL,
  `rh` VARCHAR(4) NOT NULL,
  `eps` VARCHAR(15) NOT NULL,
  `fechaNacimiento` DATETIME NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPersona_UNIQUE` ON `mydb`.`persona` (`idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`persona_has_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persona_has_rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persona_has_rol` (
  `persona_idPersona` INT NOT NULL,
  `rol_idrol` TINYINT(2) NOT NULL,
  PRIMARY KEY (`persona_idPersona`, `rol_idrol`),
  CONSTRAINT `fk_persona_has_rol_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `mydb`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_has_rol_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `mydb`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_persona_has_rol_rol1_idx` ON `mydb`.`persona_has_rol` (`rol_idrol` ASC) VISIBLE;

CREATE INDEX `fk_persona_has_rol_persona1_idx` ON `mydb`.`persona_has_rol` (`persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`profesor_asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profesor_asignatura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profesor_asignatura` (
  `persona_idPersona` INT NOT NULL,
  `asignatura_idAsignatura` INT NOT NULL,
  PRIMARY KEY (`persona_idPersona`, `asignatura_idAsignatura`),
  CONSTRAINT `fk_persona_has_asignatura_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `mydb`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_has_asignatura_asignatura1`
    FOREIGN KEY (`asignatura_idAsignatura`)
    REFERENCES `mydb`.`asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_persona_has_asignatura_asignatura1_idx` ON `mydb`.`profesor_asignatura` (`asignatura_idAsignatura` ASC) VISIBLE;

CREATE INDEX `fk_persona_has_asignatura_persona1_idx` ON `mydb`.`profesor_asignatura` (`persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `idrol` TINYINT(2) NOT NULL,
  `value` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `value_UNIQUE` ON `mydb`.`rol` (`value` ASC) VISIBLE;

CREATE UNIQUE INDEX `idrol_UNIQUE` ON `mydb`.`rol` (`idrol` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
